set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_SKIP_RPATH TRUE)

set(CMAKE_C_FLAGS_DEBUG "" CACHE STRING "Debug CFLAGS")
set(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "Debug CXXFLAGS")
set(CMAKE_C_FLAGS_RELEASE " -DNDEBUG" CACHE STRING "Release CFLAGS")
set(CMAKE_CXX_FLAGS_RELEASE " -DNDEBUG" CACHE STRING "Release CXXFLAGS")

set(CMAKE_C_FLAGS
    "-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64"
    CACHE STRING "Default CFLAGS")

set(CMAKE_CXX_FLAGS
    "-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64"
    CACHE STRING "Default CXXFLAGS")

set(CMAKE_C_FLAGS_RELWITHDEBINFO
        "-DNDEBUG -Wno-error=sign-compare -Wno-error=stringop-truncation"
        CACHE STRING "RelWithDebInfo CFLAGS")

set(CMAKE_CXX_FLAGS_RELWITHDEBINFO
        "-DNDEBUG -Wno-error=sign-compare -Wno-error=stringop-truncation"
        CACHE STRING "RelWithDebInfo CXXFLAGS")
